image: golang:1.9
cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - go get -v -d ./...

unit_tests:
  stage: test
  script:
    - go test ./...
build:
  stage: build
  script:
    - make
